
const positivePhrases = [
  "You make me smile",
  "I think about you when we’re apart",
  "My world is better with you in it",
  "I will do my best to keep you safe",
  "Sometimes I will say no",
  "I have faith in you",
  "I know you can handle it",
  "You are creative",
  "Trust your instincts",
  "Your ideas are worthwhile",
  "You are capable",
  "You are deserving",
  "You are strong",
  "You can say no",
  "Your choices matter",
  "You make a difference",
  "Your words are powerful",
  "Your actions are powerful",
  "Your emotions may be powerful",
  "And you can still choose your actions",
  "You are more than your emotions",
  "You are a good friend",
  "You are kind",
  "You don’t have to like what someone is saying in order to treat them with respect",
  "Someone else’s poor behavior is not an excuse for your own",
  "You are imperfect",
  "So am I",
  "You can change your mind",
  "You can learn from your mistakes",
  "You can ask for help",
  "You are learning",
  "You are growing",
  "Growing is hard work",
  "I believe you",
  "I believe in you",
  "You are valuable",
  "You are interesting",
  "You are beautiful",
  "When you make a mistake, you are still beautiful",
  "Your body is your own",
  "You have say over your body",
  "You are important",
  "Your ideas matter",
  "You are able to do work that matters",
  "I see you working and learning every day",
  "You make a difference in my life",
  "I am curious what you think",
  "How did you do that?",
  "Your ideas are interesting",
  "You’ve made me think of things in a completely new way",
  "I’m excited to see what you do",
  "Thanks for helping me",
  "Thank you for contributing to our family",
  "I enjoy your company",
  "It’s fun to do things with you",
  "I’m glad you’re here",
  "I’m happy to talk with you",
  "I’m ready to listen",
  "I’m listening",
  "I’m proud of you",
  "I’m grateful you’re in my life",
  "You make me smile",
  "I love you",
];