# this one is super CI that does everything, just to save a bit of free tear CI time

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Read secrets into files
      run: |
        echo "${{ secrets.B64_PROPERTIES }}" | base64 --decode > android/upload-keystore.properties
        echo "${{ secrets.B64_RELEASE_KEY }}" | base64 --decode > android/app/upload-keystore.jks
        echo "${{ secrets.GOGOLE_SERVICE_ACCOUNT_JSON }}" | base64 --decode > gsa.json
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release
    - run: flutter build appbundle --release
    - name: Save build apk
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk
    - name: Save build aab
      uses: actions/upload-artifact@v3
      with:
        name: flutter-aab
        path: build/app/outputs/bundle/release/
#     https://github.com/r0adkll/upload-google-play
    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: gsa.json
        packageName: com.sukinsan.babysittercalculator
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: internal
        status: completed
#    - name: Upload artifact to Firebase App Distribution
#      uses: wzieba/Firebase-Distribution-Github-Action@v1
#      with:
#        appId: romeo-papa
#        serviceCredentialsFile: gsa.json
#        groups: dev
#        file: build/app/outputs/bundle/release/app-release.aab

